### ISSUE TITLE
allelecounter.exe

### ISSUE THREAD

**Issue by smithcg02** [Wedge-Oxford/battenberg#23]
Hello. Where and how can one get access to the allelecounter.exe that is required for this to run? 
Apologies if I'm missing something really obvious but I've been searching for a while and can't find it. There is a allelecounter.PY file here https://github.com/secastel/allelecounter but this doesn't work with the script I'm trying to use that relies on the .exe
Thanks in advance for your help
CGS (CRUK CI)

**Comment by keiranmraine** [comment]
The alleleCounter code is part of this project:  https://github.com/cancerit/alleleCount

You can also use cgpBattenberg to simplify execution: https://github.com/cancerit/cgpBattenberg

**Comment by keiranmraine** [comment]
As described here: https://github.com/Wedge-Oxford/battenberg#advised-installation-and-running-instructions

**Comment by lassefolkersen** [comment]
I can't find this alleleCounter_exe and I've tried to follow the links above. Any chance this could be clarified?
