### ISSUE TITLE
 Callsubclones error

### ISSUE THREAD

**Issue by mjz1** [Wedge-Oxford/battenberg#24]
Hi there,

Getting an error in the callsubclones step:
Error in t.test.default(logR[logR$Chromosome == subclones$chr[i - 1] & :
not enough 'x' observations
Calls: callSubclones -> merge_segments -> t.test -> t.test.default

Not sure if it is related, but the fitcn step mentions that 'reference segment did not provide a possible solution':
[1] "ploidy=1.78246500278682,rho=0.81,goodness=84.6365342478127,percentzero=0.292220227244316, perczerAbb=0.292220227244316"
[1] "ploidy=3.51630145168029,rho=0.68,goodness=77.8766478542867,percentzero=0.289668502443199, perczerAbb=0.289668502443199"
[1] "goodnessOfFit from grid=0.52666849231385"
[1] "reference segment did not provide a possible solution"

I have this pipeline working for the majority of my samples, but would like to know if there is a way to resolve these sorts of issues. It results in the finalise step failing as it can't find the subclones.txt file. Are these samples for which there is simply no solution?

Any help would be greatly appreciated! Thanks!

**Comment by sdentro** [comment]
This has been fixed in dev and goes into the next release, which should be out later today

**Comment by keiranmraine** [comment]
@sdentro we have a feature release of cgpBattenberg in the works so we can pull in the new version into that when it goes live if you drop me a line.
