### ISSUE TITLE
Ref files for hg38

### ISSUE THREAD

**Issue by phuchoang1012** [Wedge-Oxford/battenberg#25]
Hello,

Do you currently offer reference files for hg38? If not, would you recommend just using Liftover?

Thank you!

**Comment by aganezov** [comment]
Hi @phuchoang1012 , have you found/generated hg38 ref files?

**Comment by phuchoang1012** [comment]
Hi @aganezov, I was suggested by the author to perform liftover for hg38 ref files.

**Comment by aganezov** [comment]
@phuchoang1012 have you been able to produce the files? 
I believe one needs 1000g files, impute, probloci, and gc correction files.
