### ISSUE TITLE
Subclones output file

### ISSUE THREAD

**Issue by kathryn-beal** [Wedge-Oxford/battenberg#29]
Hi,
A scientist in our group has found a case where the cellular fraction (frac2_A) of the nMaj2_A and nMin2_A columns has a higher value than frac1_A from the callSubclones subroutine (version 2.2.5). We would be very grateful if you could explain why this is the case.

For example:

zcat subclones.txt.gz | awk 'BEGIN{ FS=OFS="\t" }{ print $1,$2,$3,$8,$9,$10,$11,$12,$13 }' | column -t | less -S
chr  startpos   endpos     nMaj1_A  nMin1_A  frac1_A            nMaj2_A  nMin2_A  frac2_A
...
12   19462666   19698320   3        0        0.381011741894733  3        1        0.618988258105267
...
12   37866866   83372701   2        1        0.431746072237525  3        1        0.568253927762475
...
12   83501125   133836024  2        0        0.332939966391955  2        1        0.667060033608045
...

Are these fractions supposed to be listed with major fraction on the left and minor fraction on the right, which is not what we are seeing here?
Regards
Kathryn

**Comment by sdentro** [comment]
Hi Kathryn,

The solutions are not sorted by the proportion of tumour cells estimates. So it's entirely possible for the larger proportion to be mentioned second, there is no special meaning.

Best,
Stefan
