### ISSUE TITLE
error when producing sunRise plot

### ISSUE THREAD

**Issue by kathryn-beal** [Wedge-Oxford/battenberg#30]
Hi,
We have a case where no copy number solutions have been found for a data set, with the appropriate message written to the cnaStatusFile. However, we then get an error when trying to produce the sunrise plot:
`Error in if (psi_opt1 > 0 && rho_opt1 > 0) { :
  missing value where TRUE/FALSE needed`
`Calls: fit.copy.number -> runASCAT -> <Anonymous>`
`In addition: Warning message:`
`In log(d) : NaNs produced`

Should the code exit if no copy number solutions have been found and not try to create a sunrise plot? If it is possible to produce a valid sunrise plot in this case, would it possible for you to suggest a cause for the error we are seeing?
Regards
Kathryn

**Comment by sdentro** [comment]
Hi Kathryn,

Apologies for getting back to you so late. I think it would be good to at least provide the plot, as one may want to see what the solution landscape looks like, even though Battenberg did not find a suitable solution. The ascat.plotSunrise function does not plot the "X" when rho_opt1 and psi_opt1 are set to anything equalling zero or lower, so that seems to be an easy solution. I'll get that sorted.

Best wishes,
Stefan

**Comment by sdentro** [comment]
Just pushed a fix to the [dev branch](https://github.com/Wedge-Oxford/battenberg/commit/25aba16f112b6b1017aa8a9c920d3498c8e259e6). Could you please confirm that this fixes the issue for you?

**Comment by kathryn-beal** [comment]
Hi Stefan,
Thank you for looking into this and sorry for taking a while to test this out. I now get a sunrise plot, however, there is a new error:
Parsed with column specification:
cols(
  Chromosome = col_integer(),
  Position = col_integer(),
  PD39454a = col_integer()
)
Parsed with column specification:
cols(
  Chromosome = col_integer(),
  Position = col_integer(),
  PD39454a = col_double()
)
Error in if ((psi_optimum - 0.5 * psi_range) < psi_min_initial) { : 
  missing value where TRUE/FALSE needed
Calls: fit.copy.number -> run_clonal_ASCAT -> get_new_bounds
In addition: Warning message:
In log(d) : NaNs produced
Execution halted
Command exited with non-zero status 1

Regards
Kathryn

**Comment by sdentro** [comment]
Hi Kathryn,

Thanks for getting back to me. I've overlooked that the rho/psi 
optimisation step obviously doesn't work when there is no rho/psi.. I 
believe there are two options: 1) stop the pipeline after no solution is 
found or 2) set placeholder values and fit a profile. Both will be a 
change in the R code and the Perl code (not all regular Battenberg 
output files are produced). I'll have a chat with David W. and get back 
to you.

Best wishes,

Stefan


On 27/11/2018 14:18, kathryn-beal wrote:
>
> Hi Stefan,
> Thank you for looking into this and sorry for taking a while to test 
> this out. I now get a sunrise plot, however, there is a new error:
> Parsed with column specification:
> cols(
> Chromosome = col_integer(),
> Position = col_integer(),
> PD39454a = col_integer()
> )
> Parsed with column specification:
> cols(
> Chromosome = col_integer(),
> Position = col_integer(),
> PD39454a = col_double()
> )
> Error in if ((psi_optimum - 0.5 * psi_range) < psi_min_initial) { :
> missing value where TRUE/FALSE needed
> Calls: fit.copy.number -> run_clonal_ASCAT -> get_new_bounds
> In addition: Warning message:
> In log(d) : NaNs produced
> Execution halted
> Command exited with non-zero status 1
>
> Regards
> Kathryn
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Wedge-2DOxford_battenberg_issues_30-23issuecomment-2D442073879&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PAnfbuR88tbRptAA1gUdGM7Zh0wY0VmxOa6Qo-6JsLk&m=PsFNmO9vzQeAZNnwlezHIYo2CZR7IQz8zGRhtrfTmIY&s=9M3GM02KQUZOaSTH2SDeOnpJlw-7YiEH_Xht6ek5oyU&e=>, 
> or mute the thread 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AD3tQDdthp2lYzBuby0dA15miVk6Q76Zks5uzUm0gaJpZM4Wm4t4&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PAnfbuR88tbRptAA1gUdGM7Zh0wY0VmxOa6Qo-6JsLk&m=PsFNmO9vzQeAZNnwlezHIYo2CZR7IQz8zGRhtrfTmIY&s=km5aRmnHJLecrtaiQI4cNPzI_yj5SVkIAmRCfS_R9yw&e=>.
>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
