### ISSUE TITLE
[E::hts_idx_push] Unsorted positions on sequence #6: 135999720 followed by 1

### ISSUE THREAD

**Issue by TakaYamaguchi** [Wedge-Oxford/battenberg#34]
Hi,

As I posted at https://github.com/cancerit/cgpBattenberg/issues/94, would you be able to add options(scipen = 999) to the battenberg R codes so that users don't have to change the default Rprofile file?

Thanks,

Taka

**Comment by davidwedge** [comment]
Hi Taka,
Thank you for the suggestion. We’re planning to introduce this in the next Battenberg release.
Best,
David

**Comment by sdentro** [comment]
This is now added in the dev branch. Thanks for reporting @TakaYamaguchi !

**Comment by TakaYamaguchi** [comment]
Thank you!

Taka
