### ISSUE TITLE
plot error  at plothaplotypes.23.

### ISSUE THREAD

**Issue by TakaYamaguchi** [Wedge-Oxford/battenberg#35]
Hi,

Some samples had this error below at plothaplotypes.23. It seems that chrX caused some issues. Have you guys seen this error before?

 Calls: plot.haplotype.data ... create.haplotype.plot -> plot -> plot.default -> localWindow -> plot.window
In addition: Warning messages:
1: In min(mut_data$Position, na.rm = T) :
  no non-missing arguments to min; returning Inf
2: In max(mut_data$Position, na.rm = T) :
  no non-missing arguments to max; returning -Inf
3: In min(x) : no non-missing arguments to min; returning Inf
4: In max(x) : no non-missing arguments to max; returning -Inf
Execution halted

Thanks,

Taka

**Comment by sdentro** [comment]
Hello Taka,

This error occurs when there are no heterozygous SNPs on the X chromosome. Just to double check, did you exclude X from analysis (i.e. via cgpBattenberg's ignore file)?

Regardless, a fix is in place in the dev branch of this repository that you're welcome to try out. The new release is still in testing, is hopefully done in a week or two.

**Comment by TakaYamaguchi** [comment]
Hi Stefan,

Thanks for the comment. Yes, I encountered the error when the X chr was included. (I've excluded it since then)

Thanks,

Taka

**Comment by sdentro** [comment]
OK, glad it's worked out!
