### ISSUE TITLE
difference between sublones.txt and subclones_1.txt

### ISSUE THREAD

**Issue by Sames-Jtudd** [Wedge-Oxford/battenberg#40]
Hi, 
when running the call_subclones command of the Battenberg pipe line two sublcones files are generated. 

subclones_1.txt (generated first and usually with more CN segments 
sublones.txt 

this appears to be independent of the number of copy number solutions for that sample.
What is the difference? 

many thanks 

Jamie

**Comment by davidwedge** [comment]
merged into #41
