### ISSUE TITLE
step producing file <tumour_sample>_battenberg_cn.vcf.gz

### ISSUE THREAD

**Issue by jazberna1** [Wedge-Oxford/battenberg#41]
Hello Dave,

I was wondering if you could let me know which step of battenberg.pl produces these two files:
<tumour_sample>_battenberg_cn.vcf.gz
<tumour_sample>_battenberg_cn.vcf.gz.tbi

The reason for asking is that I cannot find them and yet the pipeline seems completed.

Many thanks
Jorge

**Comment by Sames-Jtudd** [comment]
I thinks this is caveman/ASCAT output and not generated by the current battenberg pipe. 
I believe the "subclones.txt" file has the same data ie segment CN data.

**Comment by jazberna1** [comment]
Dear Sames,

Thanks so much for the clarification.

That file you mention "subclones.txt", which is indeed produced, does it contain the actual CN values as they are displayed in the segmentation plots?

Many thanks
Jorge

**Comment by Sames-Jtudd** [comment]
Im going to say yes. To be honest Im not entirely sure what the exact realationship between the subclones file and the copy number profiles is. I can't reconcile them, completely.  It would be great to have some input from a Battenberg pro!

**Comment by keiranmraine** [comment]
`battenberg.pl` is part of [cgpBattenberg](https://github.com/cancerit/cgpBattenberg) and handles conversion into more widely standardised bioinformatic files.

* [battenberg_CN_to_VCF.pl](https://github.com/cancerit/cgpBattenberg/blob/dev/perl/bin/battenberg_CN_to_VCF.pl) converts the subclones file to a VCF file
* [bb_vcf_to_ascat_cn.pl](https://github.com/cancerit/cgpBattenberg/blob/dev/perl/bin/bb_vcf_to_ascat_cn.pl) reads the major CN and generates a simple segment bed file

**Comment by davidwedge** [comment]
The subclones.txt file contains the copy number calls. The subclones_1.txt file is produced before the subclones.txt file, the difference between the two being that adjacent segments with the same copy number are merged. The subclones.txt file contains exactly the same subclones as those shown in the subclones.png (and summarised genomewide in the _subclones.png and _average.png files), in the '*_A' columns.

**Comment by jazberna1** [comment]
Hello all,

Thanks so much for the replies.

Jorge

**Comment by Sames-Jtudd** [comment]
ditto. 
thanks
