### ISSUE TITLE
correspondence between _A  columns in the _subclones.txt and BattenbergProfile_subclones.png

### ISSUE THREAD

**Issue by jazberna1** [Wedge-Oxford/battenberg#42]
Hello,

I was wondering if you could please help me to interpret the Battenberg output, which has given me two subclones. I understand the _A columns in the _subclones.txt match somehow segmetation plot in BattenbergProfile_subclones.png.

As I have two subclones, am I right saying that the columns nMaj1_A, nMin1_A contain the CN segments for one clone and the columns nMaj2_A, nMin2_A contain the CN for the other clone?

Then in the BattenbergProfile_subclones.png I see two different colours (as in ASCAT) and then thick and thin lines. Do the thick lines corrrespond to one clone and the thin ones to the other?

Thanks so much
Jorge

**Comment by davidwedge** [comment]
Yes, your interpretation is correct. In the subclones.png file, both subclones are shown, with the major subclone (CCF>50%) shown as a thicker line.

**Comment by jazberna1** [comment]
Hello Dave,

Thanks so much for clarifying. I have attached the output of my Battenberg run. In the top left plot I see I have two subclones (the two 'X'). Then in the subclones plot I see that for chromosome four both subclones have the same 'major' subclone CN3 and CN1 profile. However in the _subclones.txt I see that the major subclone has a CN2 and CN1 profile. The other subclone has NA as expected since there are no thinlines in the plot. In summary I see that both subclones have the same CN profile but there is a disagreement between the txt and the png files.

Am I doing something wrong with my interpretations? 

Thanks so much and apologies for these many likely naive questions.
Jorge

<img width="1170" alt="Screenshot 2020-01-31 at 15 16 50" src="https://user-images.githubusercontent.com/27732589/73546744-04f44580-443e-11ea-92bc-5ac226ffb5b9.png">

**Comment by davidwedge** [comment]
Yes this is correct. Also, please note that the orange and grey lines show total and minor (not major and minor) copy number, i.e. the orange lines shows nmaj + nmin.

**Comment by jazberna1** [comment]
Hello Dave,

Thanks you much ! All clear now
Regards
Jorge
